name: test-builds 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every month on the 1st
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    
    name: Py ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: |
        # The ~= operator will choose the latest PATCH release within MAJOR.MINOR version specified
        # See https://stackoverflow.com/a/50080281/6615512 
        # and https://www.python.org/dev/peps/pep-0440/#compatible-release
        pip install rasterio geopandas
